Feature: add array operators
nestjsx/crud pull request #754
Opened 2021-12-07 00:42 UTC by emmanuel

Adds new `contArr` and `intersectsArr` query operators, with the `intersectsArr` operator generating SQL queries like:

```
select ... where tags::text[] && ARRAY[$1,$2];
```

This selects rows where the `tags` column, which is presumed to be of type `text[]`, contains at least one value that equals `$1` or `$2`. 

Fixes #687

2021-12-07 00:46 UTC, emmanuel commented
We currently use this patch on top of 4.6.2. I'd be happy to open a PR for 4.6.x, if someone will create a branch I can use as a PR target.

2022-08-04 10:30 UTC, BenStirrup commented
Good initiative and indeed welcomed feature ! 
@michaelyali when you have time, could you review it ?

2023-04-30 14:04 UTC, bestori reviewed
A small question

2023-04-30 14:04 UTC, bestori commented on packages/crud-request/src/types/request-query.types.ts
> -  $eq?: SFiledValues;
Why is this block (`$eq?:...` to `notinL`) marked deleted? Looks like an indent issue with your code editor of choice...?

2023-04-30 14:04 UTC, bestori requested changes
Please merge with main or close :O)

2023-11-01 06:44 UTC, afilp commented
@emmanuel Hi, since this repo seems to be obsolete, can you please check the same PR code in the new (maintained) fork here?
https://github.com/gid-oss/dataui-nestjs-crud/issues/19
https://github.com/gid-oss/dataui-nestjs-crud/pull/21

If you wish I can delete my PR and you can create a new one there. (I created it there using your code because I was asked to)

Thanks a lot!

2026-08-03 06:34 UTC, closed without merging